// packages/solid/src/components/button.ts
/** Headless Base UI-shaped Button: a focusable `div` that acts like `<button>`. */

import { splitProps, type JSX } from "solid-js"
import type { EventPayload } from "@gpuix/native"
import type { HostProps, KeyEvent } from "@gpuix/native/host"
import { renderSlot, resolveStyle, type StateStyle } from "./floating.js"

export interface ButtonState {
  disabled: boolean
}

export interface ButtonBehavior {
  disabled?: boolean
  /** Keep a disabled button in the Tab order, for example while it saves. */
  focusableWhenDisabled?: boolean
  onClick?: (event: EventPayload) => void
  onKeyDown?: (event: KeyEvent) => void
  onKeyUp?: (event: KeyEvent) => void
  tabIndex?: number
}

/**
 * Props that make any element act like a `<button>`: a tab stop, `role`, and
 * `onClick` from a press, Enter (on key down) or Space (on key up), like a
 * browser. Reads `behavior` lazily, so a reactive `disabled` stays live.
 * Primitives such as `DialogTrigger` build on it.
 */
export function buttonProps(behavior: ButtonBehavior): Record<string, unknown> {
  const disabled = () => behavior.disabled ?? false
  return {
    role: "button",
    // Unset keeps an `asChild` child's own tabIndex; renderSlot defaults to 0.
    get tabIndex() {
      return disabled() && !behavior.focusableWhenDisabled ? -1 : behavior.tabIndex
    },
    onClick(event: EventPayload) {
      if (!disabled()) behavior.onClick?.(event)
    },
    onKeyDown(event: KeyEvent) {
      behavior.onKeyDown?.(event)
      if (disabled() || event.defaultPrevented) return
      if (event.key === "enter" && !event.isHeld) behavior.onClick?.(event)
      // Space would otherwise scroll or type; it fires on release.
      if (event.key === "space") event.preventDefault()
    },
    onKeyUp(event: KeyEvent) {
      behavior.onKeyUp?.(event)
      if (!disabled() && !event.defaultPrevented && event.key === "space") {
        behavior.onClick?.(event)
      }
    },
  }
}

export interface ButtonProps
  extends Omit<HostProps, "style" | "onClick" | "onKeyDown" | "onKeyUp">, ButtonBehavior {
  children?: JSX.Element
  asChild?: boolean
  style?: StateStyle<ButtonState>
}

export function Button(allProps: ButtonProps): JSX.Element {
  const [behavior, local, props] = splitProps(
    allProps,
    ["disabled", "focusableWhenDisabled", "onClick", "onKeyDown", "onKeyUp", "tabIndex"],
    ["asChild", "children", "style"]
  )
  const button = buttonProps(behavior)
  return renderSlot({
    asChild: local.asChild,
    children: local.children,
    props: Object.defineProperties(
      { ...props },
      {
        ...Object.getOwnPropertyDescriptors(button),
        style: {
          enumerable: true,
          get: () => resolveStyle(local.style, { disabled: behavior.disabled ?? false }),
        },
      }
    ),
    defaultTabIndex: 0,
  })
}

// packages/react/src/components/button.tsx
/** Headless Base UI-shaped Button: a focusable `div` that acts like `<button>`. */

import { forwardRef } from "react"
import type { ReactElement, ReactNode } from "react"
import type { EventPayload } from "@gpuix/native"
import type { KeyEvent, Props, PublicInstance, StyleDesc } from "../types/host.js"
import { renderSlot, resolveStyle, type StateStyle } from "./floating.js"

export interface ButtonState {
  disabled: boolean
}

export interface ButtonBehavior {
  disabled?: boolean
  /** Keep a disabled button in the Tab order, for example while it saves. */
  focusableWhenDisabled?: boolean
  onClick?: (event: EventPayload) => void
  onKeyDown?: (event: KeyEvent) => void
  onKeyUp?: (event: KeyEvent) => void
  tabIndex?: number
}

/**
 * Props that make any element act like a `<button>`: a tab stop, `role`, and
 * `onClick` from a press, Enter (on key down) or Space
 * (on key up), like a browser. Primitives such as `Dialog.Trigger` build on it.
 */
export function buttonProps({
  disabled = false,
  focusableWhenDisabled = false,
  onClick,
  onKeyDown,
  onKeyUp,
  tabIndex,
}: ButtonBehavior): Props {
  return {
    role: "button",
    // Unset keeps an `asChild` child's own tabIndex; renderSlot defaults to 0.
    tabIndex: disabled && !focusableWhenDisabled ? -1 : tabIndex,
    onClick: (event: EventPayload) => {
      if (!disabled) onClick?.(event)
    },
    onKeyDown: (event: KeyEvent) => {
      onKeyDown?.(event)
      if (disabled || event.defaultPrevented) return
      if (event.key === "enter" && !event.isHeld) onClick?.(event)
      // Space would otherwise scroll or type; it fires on release.
      if (event.key === "space") event.preventDefault()
    },
    onKeyUp: (event: KeyEvent) => {
      onKeyUp?.(event)
      if (!disabled && !event.defaultPrevented && event.key === "space") onClick?.(event)
    },
  }
}

export interface ButtonProps extends Omit<Props, "style" | "onClick" | "onKeyDown" | "onKeyUp">, ButtonBehavior {
  children?: ReactNode
  asChild?: boolean
  style?: StateStyle<ButtonState>
}

export const Button = forwardRef<PublicInstance, ButtonProps>(function Button(
  {
    asChild,
    children,
    style,
    disabled = false,
    focusableWhenDisabled,
    onClick,
    onKeyDown,
    onKeyUp,
    tabIndex,
    ...props
  },
  ref
): ReactElement {
  const state: ButtonState = { disabled }
  return renderSlot({
    asChild,
    children,
    props: {
      ...props,
      ...buttonProps({ disabled, focusableWhenDisabled, onClick, onKeyDown, onKeyUp, tabIndex }),
      style: resolveStyle(style, state) as StyleDesc | undefined,
    },
    ref,
    defaultTabIndex: 0,
  })
})
