// packages/solid/src/components/dialog.ts
/** Headless Base UI-shaped Dialog over a full-window GPUIX anchored layer. */

import {
  createComponent,
  createContext,
  createSignal,
  Show,
  splitProps,
  useContext,
  type JSX,
} from "solid-js"
import type { EventPayload } from "@gpuix/native"
import { resolveFocusTarget } from "@gpuix/native/host"
import type { FocusTarget, HostProps, KeyEvent } from "@gpuix/native/host"
import type { HostElement } from "../host.js"
import { jsx } from "../jsx-runtime.js"
import { useGpuixRequired } from "../root.js"
import { DismissableLayer, renderSlot } from "./floating.js"

interface DialogState {
  open(): boolean
  modal(): boolean
  setOpen(open: boolean): void
  pointerDismissal(): boolean
  trigger: { current: HostElement | null }
}

const DialogContext = createContext<DialogState>()
function context(name: string): DialogState {
  const value = useContext(DialogContext)
  if (!value) throw new Error(`${name} must be used inside Dialog`)
  return value
}

/** Enter and Space activate a focused part, like a `<button>`. */
function isActivationKey(event: KeyEvent): boolean {
  return event.key === "enter" || event.key === "space"
}

export interface DialogProps {
  children?: JSX.Element
  open?: boolean
  defaultOpen?: boolean
  onOpenChange?: (open: boolean) => void
  /** Default true: blocks the page behind, keeps Tab inside the popup. */
  modal?: boolean
  /** Keep the dialog open when the backdrop is pressed. */
  disablePointerDismissal?: boolean
}

export function Dialog(props: DialogProps): JSX.Element {
  const [internalOpen, setInternalOpen] = createSignal(props.defaultOpen ?? false)
  const open = () => props.open === undefined ? internalOpen() : props.open
  const state: DialogState = {
    open,
    modal: () => props.modal ?? true,
    pointerDismissal: () => !props.disablePointerDismissal,
    trigger: { current: null },
    setOpen(next) {
      const previous = open()
      if (previous === next) return
      if (props.open === undefined) setInternalOpen(next)
      props.onOpenChange?.(next)
    },
  }
  return createComponent(DialogContext.Provider, {
    value: state,
    get children() { return props.children },
  })
}

export interface DialogTriggerProps extends HostProps {
  children?: JSX.Element
  asChild?: boolean
  ref?: (element: HostElement) => void
}

export function DialogTrigger(props: DialogTriggerProps): JSX.Element {
  const state = context("DialogTrigger")
  return renderSlot({
    asChild: props.asChild,
    children: props.children,
    props: {
      ...props,
      ref(element: HostElement) {
        state.trigger.current = element
        props.ref?.(element)
      },
      get "aria-expanded"() { return state.open() },
      onClick(event: EventPayload) {
        props.onClick?.(event)
        state.setOpen(true)
      },
      onKeyDown(event: KeyEvent) {
        props.onKeyDown?.(event)
        if (isActivationKey(event)) state.setOpen(true)
      },
    },
    defaultTabIndex: 0,
  })
}

export interface DialogPortalProps extends HostProps {
  children?: JSX.Element
}

/**
 * A full-window layer painted after the page, so it covers `<virtual-list>`
 * and everything else. Mounted only while the dialog is open.
 */
export function DialogPortal(props: DialogPortalProps): JSX.Element {
  const state = context("DialogPortal")
  return createComponent(Show, {
    get when() { return state.open() },
    keyed: true,
    get children() {
      return jsx("anchored", {
        ...props,
        // Native sizes the layer to the viewport, so a resize never leaves an
        // uncovered strip that clicks could reach.
        fill: "window",
        deferred: true,
        // Below menus and tooltips (priority 1), so a Select inside the popup
        // opens on top of it.
        priority: 0,
        get occlude() { return state.modal() },
        get style() {
          return {
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            // Explicit transparent: the Backdrop paints the dim, not the layer.
            backgroundColor: "transparent",
            ...props.style,
            pointerEvents: state.modal() ? props.style?.pointerEvents : "none",
          }
        },
        get children() { return props.children },
      })
    },
  })
}

export interface DialogBackdropProps extends HostProps {
  children?: JSX.Element
}

/** Covers the window behind the popup. A press on it closes the dialog. */
export function DialogBackdrop(props: DialogBackdropProps): JSX.Element {
  const state = context("DialogBackdrop")
  return jsx("div", {
    ...props,
    get style() {
      return { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, ...props.style }
    },
    onMouseDown(event: EventPayload) {
      props.onMouseDown?.(event)
      if (state.pointerDismissal()) state.setOpen(false)
    },
  })
}

export interface DialogPopupProps extends HostProps {
  children?: JSX.Element
  ref?: (element: HostElement) => void
  /** Focus on open. Default: the popup itself, so the first Tab enters it. */
  initialFocus?: FocusTarget<HostElement>
  /** Focus on close. Default: the trigger, else the element focused before open. */
  finalFocus?: FocusTarget<HostElement>
}

/** The dialog surface. Moves focus in on open and back out on close. */
export function DialogPopup(allProps: DialogPopupProps): JSX.Element {
  const [focus, props] = splitProps(allProps, ["initialFocus", "finalFocus"])
  const state = context("DialogPopup")
  const renderer = useGpuixRequired()
  let popup: HostElement | null = null
  return createComponent(Show, {
    get when() { return state.open() },
    keyed: true,
    get children() {
      return createComponent(DismissableLayer, {
        onEscapeKeyDown: () => state.setOpen(false),
        initialFocus: () => resolveFocusTarget(focus.initialFocus, () => popup?.id ?? null),
        finalFocus: (previous) =>
          resolveFocusTarget(focus.finalFocus, () => state.trigger.current?.id ?? previous),
        get children() {
          return jsx("div", {
            ...props,
            ref(element: HostElement) {
              popup = element
              props.ref?.(element)
            },
            get role() { return props.role ?? "dialog" },
            get tabIndex() { return props.tabIndex ?? -1 },
            // A press inside the popup must never reach the backdrop behind it.
            get style() { return { pointerEvents: "auto", ...props.style } },
            onKeyDown(event: KeyEvent) {
              props.onKeyDown?.(event)
              if (!state.modal() || event.key !== "tab" || event.defaultPrevented || !popup) return
              event.preventDefault()
              if (event.modifiers?.shift) renderer.focusPreviousWithin?.(popup.id)
              else renderer.focusNextWithin?.(popup.id)
            },
          })
        },
      })
    },
  })
}

export function DialogTitle(props: HostProps & { children?: JSX.Element }): JSX.Element {
  return jsx("div", { role: "heading", "aria-level": 2, ...props })
}

export function DialogDescription(props: HostProps & { children?: JSX.Element }): JSX.Element {
  return jsx("div", props as Record<string, unknown>)
}

export interface DialogCloseProps extends HostProps {
  children?: JSX.Element
  asChild?: boolean
}

export function DialogClose(props: DialogCloseProps): JSX.Element {
  const state = context("DialogClose")
  return renderSlot({
    asChild: props.asChild,
    children: props.children,
    props: {
      ...props,
      onClick(event: EventPayload) {
        props.onClick?.(event)
        state.setOpen(false)
      },
      onKeyDown(event: KeyEvent) {
        props.onKeyDown?.(event)
        if (isActivationKey(event)) state.setOpen(false)
      },
    },
    defaultTabIndex: 0,
  })
}

export {
  Dialog as Root,
  DialogBackdrop as Backdrop,
  DialogClose as Close,
  DialogDescription as Description,
  DialogPopup as Popup,
  DialogPortal as Portal,
  DialogTitle as Title,
  DialogTrigger as Trigger,
}

// packages/react/src/components/dialog.tsx
/** Headless Base UI-shaped Dialog over a full-window GPUIX anchored layer. */

import React, {
  createContext,
  forwardRef,
  useCallback,
  useContext,
  useRef,
} from "react"
import type { ReactElement, ReactNode } from "react"
import type { EventPayload } from "@gpuix/native"
import { resolveFocusTarget } from "@gpuix/native/host"
import type { FocusTarget, KeyEvent, Props, PublicInstance } from "../types/host.js"
import { useGpuix } from "../hooks/use-gpuix.js"
import {
  renderSlot,
  setRefs,
  useControllableState,
  DismissableLayer,
} from "./floating.js"

interface DialogContextValue {
  open: boolean
  modal: boolean
  disablePointerDismissal: boolean
  setOpen: (open: boolean) => void
  triggerRef: React.MutableRefObject<PublicInstance | null>
}

const DialogContext = createContext<DialogContextValue | null>(null)

function useDialogContext(name: string): DialogContextValue {
  const context = useContext(DialogContext)
  if (!context) throw new Error(`${name} must be used inside Dialog`)
  return context
}

/** Enter and Space activate a focused part, like a `<button>`. */
function isActivationKey(event: KeyEvent): boolean {
  return event.key === "enter" || event.key === "space"
}

export interface DialogProps {
  children?: ReactNode
  open?: boolean
  defaultOpen?: boolean
  onOpenChange?: (open: boolean) => void
  /** Default true: blocks the page behind, keeps Tab inside the popup. */
  modal?: boolean
  /** Keep the dialog open when the backdrop is pressed. */
  disablePointerDismissal?: boolean
}

export function Dialog({
  children,
  open: openProp,
  defaultOpen = false,
  onOpenChange,
  modal = true,
  disablePointerDismissal = false,
}: DialogProps): ReactElement {
  const [open, setOpen] = useControllableState({
    value: openProp,
    defaultValue: defaultOpen,
    onChange: onOpenChange,
  })
  const triggerRef = useRef<PublicInstance | null>(null)
  const context: DialogContextValue = {
    open,
    modal,
    disablePointerDismissal,
    setOpen,
    triggerRef,
  }
  return <DialogContext.Provider value={context}>{children}</DialogContext.Provider>
}

export interface DialogTriggerProps extends Props {
  asChild?: boolean
}

export const DialogTrigger = forwardRef<PublicInstance, DialogTriggerProps>(
  function DialogTrigger({ asChild, children, onClick, onKeyDown, ...props }, forwardedRef) {
    const context = useDialogContext("DialogTrigger")
    const { triggerRef } = context
    // Stable, so React does not detach it (set null) in the commit that
    // unmounts the popup, which is exactly when the popup reads it.
    const ref = useCallback((value: PublicInstance | null) => {
      triggerRef.current = value
      setRefs(value, forwardedRef)
    }, [triggerRef, forwardedRef])
    return renderSlot({
      asChild,
      children,
      props: {
        ...props,
        "aria-expanded": context.open,
        onClick: (event) => {
          onClick?.(event)
          context.setOpen(true)
        },
        onKeyDown: (event: KeyEvent) => {
          onKeyDown?.(event)
          if (isActivationKey(event)) context.setOpen(true)
        },
      },
      ref,
      defaultTabIndex: 0,
    })
  }
)

export interface DialogPortalProps extends Props {}

/**
 * A full-window layer painted after the page, so it covers `<virtual-list>`
 * and everything else. Mounted only while the dialog is open.
 */
export const DialogPortal = forwardRef<PublicInstance, DialogPortalProps>(
  function DialogPortal({ style, children, ...props }, ref) {
    const context = useDialogContext("DialogPortal")
    if (!context.open) return null
    const { modal } = context
    return (
      <anchored
        {...props}
        ref={ref}
        // Native sizes the layer to the viewport, so a resize never leaves an
        // uncovered strip that clicks could reach.
        fill="window"
        deferred
        // Below menus and tooltips (priority 1), so a Select inside the popup
        // opens on top of it.
        priority={0}
        occlude={modal}
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          // Explicit transparent: the Backdrop paints the dim, not the layer.
          backgroundColor: "transparent",
          ...style,
          pointerEvents: modal ? style?.pointerEvents : "none",
        }}
      >
        {children}
      </anchored>
    )
  }
)

export interface DialogBackdropProps extends Props {}

/** Covers the window behind the popup. A press on it closes the dialog. */
export const DialogBackdrop = forwardRef<PublicInstance, DialogBackdropProps>(
  function DialogBackdrop({ style, onMouseDown, ...props }, ref) {
    const context = useDialogContext("DialogBackdrop")
    return (
      <div
        {...props}
        ref={ref}
        style={{ position: "absolute", top: 0, right: 0, bottom: 0, left: 0, ...style }}
        onMouseDown={(event: EventPayload) => {
          onMouseDown?.(event)
          if (!context.disablePointerDismissal) context.setOpen(false)
        }}
      />
    )
  }
)

export interface DialogPopupProps extends Props {
  /** Focus on open. Default: the popup itself, so the first Tab enters it. */
  initialFocus?: FocusTarget<PublicInstance>
  /** Focus on close. Default: the trigger, else the element focused before open. */
  finalFocus?: FocusTarget<PublicInstance>
}

/** The dialog surface. Moves focus in on open and back out on close. */
export const DialogPopup = forwardRef<PublicInstance, DialogPopupProps>(
  function DialogPopup(
    { style, onKeyDown, initialFocus, finalFocus, tabIndex = -1, role = "dialog", ...props },
    forwardedRef
  ) {
    const context = useDialogContext("DialogPopup")
    const { renderer } = useGpuix()
    const popupRef = useRef<PublicInstance | null>(null)
    if (!context.open) return null
    return (
      <DismissableLayer
        onEscapeKeyDown={() => context.setOpen(false)}
        initialFocus={() => resolveFocusTarget(initialFocus, () => popupRef.current?.id ?? null)}
        finalFocus={(previous) =>
          resolveFocusTarget(finalFocus, () => context.triggerRef.current?.id ?? previous)
        }
      >
        <div
          {...props}
          ref={(value: PublicInstance | null) => {
            popupRef.current = value
            setRefs(value, forwardedRef)
          }}
          role={role}
          tabIndex={tabIndex}
          // A press inside the popup must never reach the backdrop behind it.
          style={{ pointerEvents: "auto", ...style }}
          onKeyDown={(event: KeyEvent) => {
            onKeyDown?.(event)
            if (!context.modal || event.key !== "tab" || event.defaultPrevented) return
            const popup = popupRef.current
            if (!popup) return
            event.preventDefault()
            if (event.modifiers?.shift) renderer?.focusPreviousWithin?.(popup.id)
            else renderer?.focusNextWithin?.(popup.id)
          }}
        />
      </DismissableLayer>
    )
  }
)

export const DialogTitle = forwardRef<PublicInstance, Props>(function DialogTitle(props, ref) {
  return <div role="heading" aria-level={2} {...props} ref={ref} />
})

export const DialogDescription = forwardRef<PublicInstance, Props>(
  function DialogDescription(props, ref) {
    return <div {...props} ref={ref} />
  }
)

export interface DialogCloseProps extends Props {
  asChild?: boolean
}

export const DialogClose = forwardRef<PublicInstance, DialogCloseProps>(
  function DialogClose({ asChild, children, onClick, onKeyDown, ...props }, ref) {
    const context = useDialogContext("DialogClose")
    return renderSlot({
      asChild,
      children,
      props: {
        ...props,
        onClick: (event) => {
          onClick?.(event)
          context.setOpen(false)
        },
        onKeyDown: (event: KeyEvent) => {
          onKeyDown?.(event)
          if (isActivationKey(event)) context.setOpen(false)
        },
      },
      ref,
      defaultTabIndex: 0,
    })
  }
)

export {
  Dialog as Root,
  DialogBackdrop as Backdrop,
  DialogClose as Close,
  DialogDescription as Description,
  DialogPopup as Popup,
  DialogPortal as Portal,
  DialogTitle as Title,
  DialogTrigger as Trigger,
}
