// packages/react/src/components/combobox.tsx
/** Headless shadcn-shaped Combobox components with native GPUI text input. */

import React, {
  createContext,
  forwardRef,
  useContext,
  useRef,
  useState,
} from "react"
import type { ReactElement, ReactNode } from "react"
import type { EventPayload } from "@gpuix/native"
import type { InputProps, KeyEvent, Props, PublicInstance } from "../types/host.js"
import { useGpuix } from "../hooks/use-gpuix.js"
import {
  FloatingLayer,
  floatingRootStyle,
  renderSlot,
  resolveStyle,
  setRefs,
  useControllableState,
  DismissableLayer,
} from "./floating.js"
import type { FloatingContentProps, StateStyle } from "./floating.js"

export type ComboboxValue = string | string[] | null

interface ComboboxContextValue {
  open: boolean
  disabled: boolean
  multiple: boolean
  value: ComboboxValue
  inputValue: string
  filteredItems: readonly string[]
  activeIndex: number | null
  inputRef: React.MutableRefObject<PublicInstance | null>
  itemToString: (item: string) => string
  setOpen: (open: boolean) => void
  setInputValue: (value: string) => void
  setActiveIndex: (index: number | null) => void
  moveActive: (delta: number) => void
  selectItem: (item: string) => void
  registerItem: (item: { value: string; disabled: boolean; mounted: boolean }) => void
}

const ComboboxContext = createContext<ComboboxContextValue | null>(null)

function useComboboxContext(name: string): ComboboxContextValue {
  const context = useContext(ComboboxContext)
  if (!context) throw new Error(`${name} must be used inside Combobox`)
  return context
}

function defaultFilter({
  items,
  query,
  itemToString,
}: {
  items: readonly string[]
  query: string
  itemToString: (item: string) => string
}): string[] {
  const normalized = query.trim().toLowerCase()
  if (!normalized) return [...items]
  const matches: Array<{ item: string; rank: number; index: number }> = []
  items.forEach((item, index) => {
    const label = itemToString(item).toLowerCase()
    const rank = label.startsWith(normalized) ? 0 : label.includes(normalized) ? 1 : null
    if (rank !== null) matches.push({ item, rank, index })
  })
  return matches
    .sort((left, right) => left.rank - right.rank || left.index - right.index)
    .map((match) => match.item)
}

export interface ComboboxProps extends Omit<Props, "children" | "onChange"> {
  children?: ReactNode
  items?: readonly string[]
  value?: ComboboxValue
  defaultValue?: ComboboxValue
  onValueChange?: (value: ComboboxValue) => void
  inputValue?: string
  defaultInputValue?: string
  onInputValueChange?: (value: string) => void
  open?: boolean
  defaultOpen?: boolean
  onOpenChange?: (open: boolean) => void
  multiple?: boolean
  disabled?: boolean
  autoHighlight?: boolean | "always"
  filter?: null | ((item: string, query: string, itemToString: (item: string) => string) => boolean)
  itemToStringValue?: (item: string) => string
}

export function Combobox({
  children,
  items = [],
  value: valueProp,
  defaultValue = null,
  onValueChange,
  inputValue: inputValueProp,
  defaultInputValue = "",
  onInputValueChange,
  open: openProp,
  defaultOpen = false,
  onOpenChange,
  multiple = false,
  disabled = false,
  autoHighlight = false,
  filter,
  itemToStringValue = (item) => item,
  style,
  ...props
}: ComboboxProps): ReactElement {
  const { renderer } = useGpuix()
  const [value, setValue] = useControllableState<ComboboxValue>({
    value: valueProp,
    defaultValue,
    onChange: onValueChange,
  })
  const [inputValue, setInputValueState] = useControllableState({
    value: inputValueProp,
    defaultValue: defaultInputValue,
    onChange: onInputValueChange,
  })
  const [open, setOpenState] = useControllableState({
    value: openProp,
    defaultValue: defaultOpen,
    onChange: onOpenChange,
  })
  const [activeIndex, setActiveIndex] = useState<number | null>(null)
  const inputRef = useRef<PublicInstance | null>(null)
  const disabledItems = useRef<string[]>([])
  const itemToString = itemToStringValue

  const filterItems = (query: string): string[] => {
    if (filter === null) return [...items]
    if (filter) {
      return items.filter((item) => filter(item, query, itemToStringValue))
    }
    return defaultFilter({ items, query, itemToString })
  }
  const filteredItems = filterItems(inputValue)

  const setOpen = (nextOpen: boolean) => {
    setOpenState(nextOpen)
    if (nextOpen) {
      queueMicrotask(() => {
        if (inputRef.current) renderer?.focusElement?.(inputRef.current.id)
      })
    }
  }

  const registerItem = ({ value: item, disabled: itemDisabled, mounted }: {
    value: string
    disabled: boolean
    mounted: boolean
  }) => {
    disabledItems.current = disabledItems.current.filter((candidate) => candidate !== item)
    if (mounted && itemDisabled) disabledItems.current.push(item)
  }

  const updateInputValue = (nextValue: string) => {
    setInputValueState(nextValue)
    const nextItems = filterItems(nextValue)
    const firstEnabled = nextItems.findIndex((item) => !disabledItems.current.includes(item))
    setActiveIndex(autoHighlight && firstEnabled >= 0 ? firstEnabled : null)
  }

  const moveActive = (delta: number) => {
    if (filteredItems.length === 0) return
    let nextIndex = activeIndex === null ? (delta > 0 ? -1 : 0) : activeIndex
    for (let checked = 0; checked < filteredItems.length; checked++) {
      nextIndex = (nextIndex + delta + filteredItems.length) % filteredItems.length
      if (!disabledItems.current.includes(filteredItems[nextIndex])) {
        setActiveIndex(nextIndex)
        return
      }
    }
  }

  const selectItem = (item: string) => {
    if (disabled || disabledItems.current.includes(item)) return
    if (multiple) {
      const selected = Array.isArray(value) ? value : []
      const exists = selected.includes(item)
      setValue(exists ? selected.filter((candidate) => candidate !== item) : [...selected, item])
      setInputValueState("")
      setActiveIndex(null)
      return
    }
    setValue(item)
    setInputValueState(itemToString(item))
    setOpen(false)
    setActiveIndex(null)
  }

  const context: ComboboxContextValue = {
    open,
    disabled,
    multiple,
    value,
    inputValue,
    filteredItems,
    activeIndex,
    inputRef,
    itemToString,
    setOpen,
    setInputValue: updateInputValue,
    setActiveIndex,
    moveActive,
    selectItem,
    registerItem,
  }

  return (
    <ComboboxContext.Provider value={context}>
      <div {...props} style={floatingRootStyle(style)}>{children}</div>
    </ComboboxContext.Provider>
  )
}

export interface ComboboxInputProps extends InputProps {
  disabled?: boolean
}

export const ComboboxInput = forwardRef<PublicInstance, ComboboxInputProps>(
  function ComboboxInput(
    { onChange, onClick, onFocus, onBlur, onKeyDown, onKeyUp, onSubmit, disabled: disabledProp, ...props },
    forwardedRef
  ) {
    const context = useComboboxContext("ComboboxInput")
    const disabled = disabledProp ?? context.disabled
    const ref = (value: PublicInstance | null) => {
      context.inputRef.current = value
      setRefs(value, forwardedRef)
    }
    return (
      <input
        {...props}
        ref={ref}
        value={context.inputValue}
        readOnly={disabled || props.readOnly}
        autoFocus={context.open}
        onClick={(event: EventPayload) => {
          onClick?.(event)
          if (!disabled) context.setOpen(true)
        }}
        onFocus={(event: EventPayload) => {
          onFocus?.(event)
          if (!disabled) context.setOpen(true)
        }}
        // Focus leaving the input closes the popup, like Base UI. Tab moves
        // focus only when no handler prevented it, so a kept Tab keeps it open.
        onBlur={(event: EventPayload) => {
          onBlur?.(event)
          context.setOpen(false)
        }}
        onChange={(event: EventPayload) => {
          onChange?.(event)
          context.setInputValue(event.value ?? "")
          if (!disabled) context.setOpen(true)
        }}
        onKeyDown={(event: KeyEvent) => {
          onKeyDown?.(event)
          if (disabled) return
          if (event.key === "down" || (event.key === "n" && event.modifiers?.ctrl)) {
            context.moveActive(1)
          } else if (event.key === "up" || (event.key === "p" && event.modifiers?.ctrl)) {
            context.moveActive(-1)
          }
        }}
        onKeyUp={(event: KeyEvent) => {
          onKeyUp?.(event)
        }}
        onSubmit={(event: EventPayload) => {
          onSubmit?.(event)
          if (disabled) return
          if (context.activeIndex !== null) {
            const item = context.filteredItems[context.activeIndex]
            if (item !== undefined) context.selectItem(item)
          }
        }}
      />
    )
  }
)

export interface ComboboxTriggerProps extends Props {
  asChild?: boolean
  disabled?: boolean
}

export const ComboboxTrigger = forwardRef<PublicInstance, ComboboxTriggerProps>(
  function ComboboxTrigger(
    { asChild, disabled: disabledProp, children, onClick, onKeyDown, ...props },
    ref
  ) {
    const context = useComboboxContext("ComboboxTrigger")
    const disabled = disabledProp ?? context.disabled
    return renderSlot({
      asChild,
      children,
      props: {
        ...props,
        tabIndex: disabled ? -1 : props.tabIndex,
        onClick: (event) => {
          onClick?.(event)
          if (!disabled) context.setOpen(!context.open)
        },
        onKeyDown: (event) => {
          onKeyDown?.(event)
          if (disabled) return
          if (event.key === "down" || event.key === "up") context.setOpen(true)
        },
      },
      ref,
      defaultTabIndex: 0,
    })
  }
)

export interface ComboboxValueProps extends Omit<Props, "children"> {
  placeholder?: ReactNode
  children?: ReactNode | ((value: ComboboxValue) => ReactNode)
}

export const ComboboxValue = forwardRef<PublicInstance, ComboboxValueProps>(
  function ComboboxValue({ placeholder, children, ...props }, ref) {
    const context = useComboboxContext("ComboboxValue")
    const value = Array.isArray(context.value)
      ? context.value.map(context.itemToString).join(", ")
      : context.value === null
        ? ""
        : context.itemToString(context.value)
    const content = typeof children === "function" ? children(context.value) : children
    return <div {...props} ref={ref}>{content ?? (value || placeholder)}</div>
  }
)

export const ComboboxContent = forwardRef<PublicInstance, FloatingContentProps>(
  function ComboboxContent({ children, onMouseDownOutside, ...props }, ref) {
    const context = useComboboxContext("ComboboxContent")
    if (!context.open) return null
    return (
      <DismissableLayer onEscapeKeyDown={() => context.setOpen(false)}>
        <FloatingLayer
          {...props}
          ref={ref}
          onMouseDownOutside={(event) => {
            onMouseDownOutside?.(event)
            context.setOpen(false)
          }}
        >
          {children}
        </FloatingLayer>
      </DismissableLayer>
    )
  }
)

export interface ComboboxListProps extends Omit<Props, "children"> {
  children?: ReactNode | ((item: string) => ReactNode)
}

export const ComboboxList = forwardRef<PublicInstance, ComboboxListProps>(
  function ComboboxList({ children, ...props }, ref) {
    const context = useComboboxContext("ComboboxList")
    return (
      <div {...props} ref={ref}>
        {typeof children === "function"
          ? context.filteredItems.map((item) => children(item))
          : children}
      </div>
    )
  }
)

export interface ComboboxItemState {
  selected: boolean
  highlighted: boolean
  disabled: boolean
}

export interface ComboboxItemProps extends Omit<Props, "children" | "style"> {
  value: string
  disabled?: boolean
  asChild?: boolean
  children?: ReactNode | ((state: ComboboxItemState) => ReactNode)
  style?: StateStyle<ComboboxItemState>
}

export const ComboboxItem = forwardRef<PublicInstance, ComboboxItemProps>(
  function ComboboxItem(
    { value, disabled = false, asChild, children, style, onClick, onMouseEnter, ...props },
    ref
  ) {
    const context = useComboboxContext("ComboboxItem")
    const index = context.filteredItems.indexOf(value)
    const selected = Array.isArray(context.value)
      ? context.value.includes(value)
      : context.value === value
    const state = { selected, highlighted: context.activeIndex === index, disabled }
    const itemRef = (instance: PublicInstance | null) => {
      context.registerItem({ value, disabled, mounted: instance !== null })
      setRefs(instance, ref)
    }
    const onItemMouseEnter = (event: EventPayload) => {
      onMouseEnter?.(event)
      if (!disabled && index >= 0) context.setActiveIndex(index)
    }
    const onItemClick = (event: EventPayload) => {
      onClick?.(event)
      if (!disabled) context.selectItem(value)
    }
    return renderSlot({
      asChild,
      children: typeof children === "function" ? children(state) : children,
      props: {
        ...props,
        style: resolveStyle(style, state),
        onMouseEnter: onItemMouseEnter,
        onClick: onItemClick,
      },
      ref: itemRef,
    })
  }
)

export const ComboboxEmpty = forwardRef<PublicInstance, Props>(
  function ComboboxEmpty(props, ref) {
    const context = useComboboxContext("ComboboxEmpty")
    return context.filteredItems.length === 0 ? <div {...props} ref={ref} /> : null
  }
)

export const ComboboxGroup = forwardRef<PublicInstance, Props>(
  function ComboboxGroup(props, ref) {
    return <div {...props} ref={ref} />
  }
)

export const ComboboxLabel = forwardRef<PublicInstance, Props>(
  function ComboboxLabel(props, ref) {
    return <div {...props} ref={ref} />
  }
)

export const ComboboxSeparator = forwardRef<PublicInstance, Props>(
  function ComboboxSeparator(props, ref) {
    return <div {...props} ref={ref} />
  }
)

export {
  Combobox as Root,
  ComboboxContent as Content,
  ComboboxEmpty as Empty,
  ComboboxGroup as Group,
  ComboboxInput as Input,
  ComboboxItem as Item,
  ComboboxLabel as Label,
  ComboboxList as List,
  ComboboxSeparator as Separator,
  ComboboxTrigger as Trigger,
  ComboboxValue as Value,
}

// packages/solid/src/components/combobox.ts
import {
  createComponent,
  createContext,
  createSignal,
  For,
  onCleanup,
  Show,
  useContext,
  type JSX,
} from "solid-js"
import type { EventPayload } from "@gpuix/native"
import type { HostProps, InputProps, KeyEvent } from "@gpuix/native/host"
import type { HostElement } from "../host.js"
import { jsx } from "../jsx-runtime.js"
import { useGpuixRequired } from "../root.js"
import {
  FloatingLayer,
  floatingRootStyle,
  renderSlot,
  resolveStyle,
  type FloatingContentProps,
  type StateStyle,
  DismissableLayer,
} from "./floating.js"

export type ComboboxValue = string | string[] | null
interface ComboContext {
  open(): boolean
  value(): ComboboxValue
  input(): string
  active(): number | null
  filtered(): string[]
  disabled: boolean
  multiple: boolean
  inputRef: { current: HostElement | null }
  setOpen(value: boolean): void
  setInput(value: string): void
  setActive(value: number | null): void
  move(delta: number): void
  select(value: string): void
  registerDisabled(value: string, disabled: boolean): () => void
}
const ComboboxContext = createContext<ComboContext>()
function context(name: string): ComboContext {
  const value = useContext(ComboboxContext)
  if (!value) throw new Error(`${name} must be used inside Combobox`)
  return value
}

export interface ComboboxProps extends HostProps {
  children?: JSX.Element
  items?: readonly string[]
  value?: ComboboxValue
  defaultValue?: ComboboxValue
  onValueChange?: (value: ComboboxValue) => void
  inputValue?: string
  defaultInputValue?: string
  onInputValueChange?: (value: string) => void
  open?: boolean
  defaultOpen?: boolean
  onOpenChange?: (open: boolean) => void
  multiple?: boolean
  disabled?: boolean
  autoHighlight?: boolean | "always"
  filter?: null | ((item: string, query: string, itemToString: (item: string) => string) => boolean)
  itemToStringValue?: (item: string) => string
}

export function Combobox(props: ComboboxProps): JSX.Element {
  const renderer = useGpuixRequired()
  const [internalValue, setInternalValue] = createSignal<ComboboxValue>(props.defaultValue ?? null)
  const [internalInput, setInternalInput] = createSignal(props.defaultInputValue ?? "")
  const [internalOpen, setInternalOpen] = createSignal(props.defaultOpen ?? false)
  const [active, setActive] = createSignal<number | null>(null)
  const inputRef: { current: HostElement | null } = { current: null }
  const disabledItems = new Set<string>()
  const value = () => props.value === undefined ? internalValue() : props.value
  const input = () => props.inputValue === undefined ? internalInput() : props.inputValue
  const open = () => props.open === undefined ? internalOpen() : props.open
  const itemToString = props.itemToStringValue ?? ((item: string) => item)
  const filtered = () => {
    const query = input().trim().toLowerCase()
    if (props.filter === null) return [...(props.items ?? [])]
    if (props.filter) return [...(props.items ?? [])].filter((item) => props.filter!(item, query, itemToString))
    return [...(props.items ?? [])].filter((item) => itemToString(item).toLowerCase().includes(query))
  }
  const setOpen = (next: boolean) => {
    const previous = open()
    if (props.open === undefined) setInternalOpen(next)
    if (previous !== next) props.onOpenChange?.(next)
    if (next) {
      queueMicrotask(() => {
        if (inputRef.current) renderer.focusElement?.(inputRef.current.id)
      })
    }
  }
  const setInput = (next: string) => {
    const previous = input()
    if (props.inputValue === undefined) setInternalInput(next)
    if (previous !== next) props.onInputValueChange?.(next)
    const nextItems = filtered()
    const firstEnabled = nextItems.findIndex((item) => !disabledItems.has(item))
    setActive(props.autoHighlight && firstEnabled >= 0 ? firstEnabled : null)
  }
  const setValue = (next: ComboboxValue) => {
    const previous = value()
    if (props.value === undefined) setInternalValue(next)
    if (!Object.is(previous, next)) props.onValueChange?.(next)
  }
  const move = (delta: number) => {
    const items = filtered()
    if (items.length === 0) return
    let next = active() === null ? (delta > 0 ? -1 : 0) : active()!
    for (let checked = 0; checked < items.length; checked += 1) {
      next = (next + delta + items.length) % items.length
      if (!disabledItems.has(items[next]!)) {
        setActive(next)
        return
      }
    }
  }
  const select = (item: string) => {
    if (props.disabled || disabledItems.has(item)) return
    if (props.multiple) {
      const current = value()
      const selected = Array.isArray(current) ? current : []
      setValue(selected.includes(item) ? selected.filter((value) => value !== item) : [...selected, item])
      setInput("")
      return
    }
    setValue(item)
    setInput(itemToString(item))
    setOpen(false)
  }
  const state: ComboContext = {
    open,
    value,
    input,
    active,
    filtered,
    disabled: props.disabled ?? false,
    multiple: props.multiple ?? false,
    inputRef,
    setOpen,
    setInput,
    setActive,
    move,
    select,
    registerDisabled(item, disabled) {
      if (disabled) disabledItems.add(item)
      return () => disabledItems.delete(item)
    },
  }
  return createComponent(ComboboxContext.Provider, {
    value: state,
    get children() {
      return jsx("div", {
        ...props,
        style: floatingRootStyle(props.style),
        get children() { return props.children },
      })
    },
  })
}

export interface ComboboxInputProps extends InputProps {
  disabled?: boolean
  ref?: (element: HostElement) => void
}
export function ComboboxInput(props: ComboboxInputProps): JSX.Element {
  const state = context("ComboboxInput")
  const disabled = () => props.disabled ?? state.disabled
  return jsx("input", {
    ...props,
    ref(element: HostElement) {
      state.inputRef.current = element
      props.ref?.(element)
    },
    get value() { return state.input() },
    get readOnly() { return disabled() || props.readOnly },
    get autoFocus() { return state.open() },
    onClick(event: EventPayload) {
      props.onClick?.(event)
      if (!disabled()) state.setOpen(true)
    },
    onFocus(event: EventPayload) {
      props.onFocus?.(event)
      if (!disabled()) state.setOpen(true)
    },
    // Focus leaving the input closes the popup, like Base UI. Tab moves focus
    // only when no handler prevented it, so a kept Tab keeps it open.
    onBlur(event: EventPayload) {
      props.onBlur?.(event)
      state.setOpen(false)
    },
    onChange(event: EventPayload) {
      props.onChange?.(event)
      state.setInput(event.value ?? "")
      if (!disabled()) state.setOpen(true)
    },
    onKeyDown(event: KeyEvent) {
      props.onKeyDown?.(event)
      if (event.key === "down") state.move(1)
      else if (event.key === "up") state.move(-1)
    },
    onSubmit(event: EventPayload) {
      props.onSubmit?.(event)
      const index = state.active()
      if (index !== null) {
        const item = state.filtered().at(index)
        if (item !== undefined) state.select(item)
      }
    },
  })
}

export interface ComboboxTriggerProps extends HostProps { children?: JSX.Element; asChild?: boolean; disabled?: boolean }
export function ComboboxTrigger(props: ComboboxTriggerProps): JSX.Element {
  const state = context("ComboboxTrigger")
  const disabled = () => props.disabled ?? state.disabled
  return renderSlot({
    asChild: props.asChild,
    children: props.children,
    props: {
      ...props,
      get tabIndex() { return disabled() ? -1 : props.tabIndex },
      onClick(event: EventPayload) {
        props.onClick?.(event)
        if (!disabled()) state.setOpen(!state.open())
      },
    },
    defaultTabIndex: 0,
  })
}

export interface ComboboxValueProps extends HostProps {
  children?: JSX.Element | ((value: ComboboxValue) => JSX.Element)
  placeholder?: JSX.Element
}
export function ComboboxValue(props: ComboboxValueProps): JSX.Element {
  const state = context("ComboboxValue")
  return jsx("div", {
    ...props,
    get children() {
      if (typeof props.children === "function") return props.children(state.value())
      if (props.children !== undefined) return props.children
      const value = state.value()
      return Array.isArray(value) ? value.join(", ") : (value ?? props.placeholder)
    },
  })
}

export function ComboboxContent(props: FloatingContentProps): JSX.Element {
  const state = context("ComboboxContent")
  return createComponent(Show, {
    get when() { return state.open() },
    keyed: true,
    get children() {
      return createComponent(DismissableLayer, {
        onEscapeKeyDown: () => state.setOpen(false),
        get children() {
          return FloatingLayer({
            ...props,
            onMouseDownOutside(event) {
              props.onMouseDownOutside?.(event)
              state.setOpen(false)
            },
          })
        },
      })
    },
  })
}

export interface ComboboxListProps extends HostProps { children?: JSX.Element | ((item: string) => JSX.Element) }
export function ComboboxList(props: ComboboxListProps): JSX.Element {
  const state = context("ComboboxList")
  return jsx("div", {
    ...props,
    get children() {
      if (typeof props.children !== "function") return props.children
      return createComponent(For, { get each() { return state.filtered() }, children: props.children })
    },
  })
}

export interface ComboboxItemState { selected: boolean; highlighted: boolean; disabled: boolean }
export interface ComboboxItemProps extends Omit<HostProps, "style"> {
  value: string
  disabled?: boolean
  asChild?: boolean
  children?: JSX.Element | ((state: ComboboxItemState) => JSX.Element)
  style?: StateStyle<ComboboxItemState>
}
export function ComboboxItem(props: ComboboxItemProps): JSX.Element {
  const state = context("ComboboxItem")
  onCleanup(state.registerDisabled(props.value, props.disabled ?? false))
  const itemState = () => ({
    selected: (() => {
      const value = state.value()
      return Array.isArray(value) ? value.includes(props.value) : value === props.value
    })(),
    highlighted: state.filtered().indexOf(props.value) === state.active(),
    disabled: props.disabled ?? false,
  })
  return renderSlot({
    asChild: props.asChild,
    get children() { return typeof props.children === "function" ? props.children(itemState()) : props.children },
    props: {
      ...props,
      get style() { return resolveStyle(props.style, itemState()) },
      onMouseEnter(event: EventPayload) {
        props.onMouseEnter?.(event)
        if (!itemState().disabled) state.setActive(state.filtered().indexOf(props.value))
      },
      onClick(event: EventPayload) {
        props.onClick?.(event)
        if (!itemState().disabled) state.select(props.value)
      },
    },
  })
}

export function ComboboxEmpty(props: HostProps & { children?: JSX.Element }): JSX.Element {
  const state = context("ComboboxEmpty")
  return createComponent(Show, {
    get when() { return state.filtered().length === 0 },
    keyed: true,
    get children() { return jsx("div", props as Record<string, unknown>) },
  })
}
const div = (props: HostProps & { children?: JSX.Element }) => jsx("div", props as Record<string, unknown>)
export const ComboboxGroup = div
export const ComboboxLabel = div
export const ComboboxSeparator = div

export {
  Combobox as Root,
  ComboboxContent as Content,
  ComboboxEmpty as Empty,
  ComboboxGroup as Group,
  ComboboxInput as Input,
  ComboboxItem as Item,
  ComboboxLabel as Label,
  ComboboxList as List,
  ComboboxSeparator as Separator,
  ComboboxTrigger as Trigger,
  ComboboxValue as Value,
}
