// packages/react/src/components/tooltip.tsx
/** Headless shadcn-shaped Tooltip components over GPUIX anchored layers. */

import React, {
  createContext,
  forwardRef,
  useContext,
  useEffect,
  useMemo,
  useRef,
} from "react"
import type { ReactElement, ReactNode } from "react"
import type { Props, PublicInstance } from "../types/host.js"
import {
  FloatingLayer,
  floatingRootStyle,
  renderSlot,
  useControllableState,
  DismissableLayer,
} from "./floating.js"
import type { FloatingContentProps } from "./floating.js"

interface TooltipProviderContextValue {
  delayDuration: number
  skipDelayDuration: number
  disableHoverableContent: boolean
  lastClosedAt: React.MutableRefObject<number>
}

const defaultProvider: TooltipProviderContextValue = {
  delayDuration: 0,
  skipDelayDuration: 300,
  disableHoverableContent: false,
  lastClosedAt: { current: Number.NEGATIVE_INFINITY },
}

const TooltipProviderContext = createContext(defaultProvider)

export interface TooltipProviderProps {
  children: ReactNode
  delayDuration?: number
  skipDelayDuration?: number
  disableHoverableContent?: boolean
}

export function TooltipProvider({
  children,
  delayDuration = 0,
  skipDelayDuration = 300,
  disableHoverableContent = false,
}: TooltipProviderProps): ReactElement {
  const lastClosedAt = useRef(Number.NEGATIVE_INFINITY)
  const value = useMemo(
    () => ({ delayDuration, skipDelayDuration, disableHoverableContent, lastClosedAt }),
    [delayDuration, skipDelayDuration, disableHoverableContent]
  )
  return <TooltipProviderContext.Provider value={value}>{children}</TooltipProviderContext.Provider>
}

interface TooltipContextValue {
  open: boolean
  disableHoverableContent: boolean
  openImmediately: () => void
  scheduleOpen: () => void
  scheduleClose: () => void
  cancelClose: () => void
  close: () => void
}

const TooltipContext = createContext<TooltipContextValue | null>(null)

function useTooltipContext(name: string): TooltipContextValue {
  const context = useContext(TooltipContext)
  if (!context) throw new Error(`${name} must be used inside Tooltip`)
  return context
}

export interface TooltipProps extends Omit<Props, "children"> {
  children?: ReactNode
  open?: boolean
  defaultOpen?: boolean
  onOpenChange?: (open: boolean) => void
  delayDuration?: number
  disableHoverableContent?: boolean
}

export function Tooltip({
  children,
  open: openProp,
  defaultOpen = false,
  onOpenChange,
  delayDuration,
  disableHoverableContent,
  style,
  ...props
}: TooltipProps): ReactElement {
  const provider = useContext(TooltipProviderContext)
  const [open, setOpenState] = useControllableState({
    value: openProp,
    defaultValue: defaultOpen,
    onChange: onOpenChange,
  })
  const openTimer = useRef<ReturnType<typeof setTimeout> | null>(null)
  const closeTimer = useRef<ReturnType<typeof setTimeout> | null>(null)
  const hoverableDisabled = disableHoverableContent ?? provider.disableHoverableContent

  const cancelOpen = () => {
    if (openTimer.current !== null) clearTimeout(openTimer.current)
    openTimer.current = null
  }
  const cancelClose = () => {
    if (closeTimer.current !== null) clearTimeout(closeTimer.current)
    closeTimer.current = null
  }
  const setOpen = (nextOpen: boolean) => {
    cancelOpen()
    cancelClose()
    setOpenState(nextOpen)
    if (!nextOpen) provider.lastClosedAt.current = Date.now()
  }
  const openImmediately = () => setOpen(true)
  const scheduleOpen = () => {
    cancelClose()
    const recentlyClosed = Date.now() - provider.lastClosedAt.current <= provider.skipDelayDuration
    const delay = recentlyClosed ? 0 : (delayDuration ?? provider.delayDuration)
    if (delay <= 0) {
      setOpen(true)
      return
    }
    cancelOpen()
    openTimer.current = setTimeout(() => setOpen(true), delay)
  }
  const close = () => setOpen(false)
  const scheduleClose = () => {
    cancelOpen()
    if (hoverableDisabled) {
      close()
      return
    }
    cancelClose()
    closeTimer.current = setTimeout(close, 80)
  }

  useEffect(() => () => {
    cancelOpen()
    cancelClose()
  }, [])

  const context: TooltipContextValue = {
    open,
    disableHoverableContent: hoverableDisabled,
    openImmediately,
    scheduleOpen,
    scheduleClose,
    cancelClose,
    close,
  }

  return (
    <TooltipContext.Provider value={context}>
      <div {...props} style={floatingRootStyle(style)}>{children}</div>
    </TooltipContext.Provider>
  )
}

export interface TooltipTriggerProps extends Props {
  asChild?: boolean
}

export const TooltipTrigger = forwardRef<PublicInstance, TooltipTriggerProps>(
  function TooltipTrigger(
    {
      asChild,
      children,
      onMouseEnter,
      onMouseLeave,
      onMouseDown,
      onClick,
      onFocus,
      onBlur,
      ...props
    },
    ref
  ) {
    const context = useTooltipContext("TooltipTrigger")
    return renderSlot({
      asChild,
      children,
      props: {
        ...props,
        onMouseEnter: (event) => {
          onMouseEnter?.(event)
          context.scheduleOpen()
        },
        onMouseLeave: (event) => {
          onMouseLeave?.(event)
          context.scheduleClose()
        },
        onMouseDown: (event) => {
          onMouseDown?.(event)
          context.close()
        },
        onClick: (event) => {
          onClick?.(event)
          context.close()
        },
        onFocus: (event) => {
          onFocus?.(event)
          context.openImmediately()
        },
        onBlur: (event) => {
          onBlur?.(event)
          context.close()
        },
      },
      ref,
      defaultTabIndex: 0,
    })
  }
)

export interface TooltipContentProps extends FloatingContentProps {}

export const TooltipContent = forwardRef<PublicInstance, TooltipContentProps>(
  function TooltipContent(
    { children, side = "top", align = "center", sideOffset = 0, onMouseEnter, onMouseLeave, ...props },
    ref
  ) {
    const context = useTooltipContext("TooltipContent")
    if (!context.open) return null
    return (
      <DismissableLayer onEscapeKeyDown={context.close}>
        <FloatingLayer
          {...props}
          ref={ref}
          side={side}
          align={align}
          sideOffset={sideOffset}
          onMouseEnter={(event) => {
            onMouseEnter?.(event)
            if (!context.disableHoverableContent) context.cancelClose()
          }}
          onMouseLeave={(event) => {
            onMouseLeave?.(event)
            context.scheduleClose()
          }}
        >
          {children}
        </FloatingLayer>
      </DismissableLayer>
    )
  }
)

export {
  Tooltip as Root,
  TooltipContent as Content,
  TooltipProvider as Provider,
  TooltipTrigger as Trigger,
}

// packages/solid/src/components/tooltip.ts
import {
  createComponent,
  createContext,
  createSignal,
  onCleanup,
  Show,
  useContext,
  type JSX,
} from "solid-js"
import type { EventPayload } from "@gpuix/native"
import type { HostProps } from "@gpuix/native/host"
import { jsx } from "../jsx-runtime.js"
import {
  FloatingLayer,
  floatingRootStyle,
  renderSlot,
  type FloatingContentProps,
  DismissableLayer,
} from "./floating.js"

interface ProviderState {
  delayDuration: number
  skipDelayDuration: number
  disableHoverableContent: boolean
  lastClosedAt: { current: number }
}
const defaultProvider: ProviderState = {
  delayDuration: 0,
  skipDelayDuration: 300,
  disableHoverableContent: false,
  lastClosedAt: { current: Number.NEGATIVE_INFINITY },
}
const ProviderContext = createContext(defaultProvider)

export interface TooltipProviderProps {
  children: JSX.Element
  delayDuration?: number
  skipDelayDuration?: number
  disableHoverableContent?: boolean
}
export function TooltipProvider(props: TooltipProviderProps): JSX.Element {
  const value: ProviderState = {
    delayDuration: props.delayDuration ?? 0,
    skipDelayDuration: props.skipDelayDuration ?? 300,
    disableHoverableContent: props.disableHoverableContent ?? false,
    lastClosedAt: { current: Number.NEGATIVE_INFINITY },
  }
  return createComponent(ProviderContext.Provider, {
    value,
    get children() { return props.children },
  })
}

interface TooltipState {
  open(): boolean
  hoverable: boolean
  openNow(): void
  scheduleOpen(): void
  scheduleClose(): void
  cancelClose(): void
  close(): void
}
const TooltipContext = createContext<TooltipState>()
function context(name: string): TooltipState {
  const value = useContext(TooltipContext)
  if (!value) throw new Error(`${name} must be used inside Tooltip`)
  return value
}

export interface TooltipProps extends HostProps {
  children?: JSX.Element
  open?: boolean
  defaultOpen?: boolean
  onOpenChange?: (open: boolean) => void
  delayDuration?: number
  disableHoverableContent?: boolean
}
export function Tooltip(props: TooltipProps): JSX.Element {
  const provider = useContext(ProviderContext)
  const [internal, setInternal] = createSignal(props.defaultOpen ?? false)
  const open = () => props.open === undefined ? internal() : props.open
  let openTimer: ReturnType<typeof setTimeout> | undefined
  let closeTimer: ReturnType<typeof setTimeout> | undefined
  const cancelOpen = () => { if (openTimer) clearTimeout(openTimer); openTimer = undefined }
  const cancelClose = () => { if (closeTimer) clearTimeout(closeTimer); closeTimer = undefined }
  const setOpen = (next: boolean) => {
    const previous = open()
    cancelOpen()
    cancelClose()
    if (props.open === undefined) setInternal(next)
    if (previous !== next) props.onOpenChange?.(next)
    if (!next) provider.lastClosedAt.current = Date.now()
  }
  const hoverable = !(props.disableHoverableContent ?? provider.disableHoverableContent)
  const state: TooltipState = {
    open,
    hoverable,
    openNow: () => setOpen(true),
    scheduleOpen() {
      cancelClose()
      const recent = Date.now() - provider.lastClosedAt.current <= provider.skipDelayDuration
      const delay = recent ? 0 : (props.delayDuration ?? provider.delayDuration)
      if (delay <= 0) setOpen(true)
      else openTimer = setTimeout(() => setOpen(true), delay)
    },
    scheduleClose() {
      cancelOpen()
      if (!hoverable) setOpen(false)
      else closeTimer = setTimeout(() => setOpen(false), 80)
    },
    cancelClose,
    close: () => setOpen(false),
  }
  onCleanup(() => { cancelOpen(); cancelClose() })
  return createComponent(TooltipContext.Provider, {
    value: state,
    get children() {
      return jsx("div", {
        ...props,
        style: floatingRootStyle(props.style),
        get children() { return props.children },
      })
    },
  })
}

export interface TooltipTriggerProps extends HostProps { children?: JSX.Element; asChild?: boolean }
export function TooltipTrigger(props: TooltipTriggerProps): JSX.Element {
  const state = context("TooltipTrigger")
  return renderSlot({
    asChild: props.asChild,
    children: props.children,
    props: {
      ...props,
      onMouseEnter(event: EventPayload) { props.onMouseEnter?.(event); state.scheduleOpen() },
      onMouseLeave(event: EventPayload) { props.onMouseLeave?.(event); state.scheduleClose() },
      onMouseDown(event: EventPayload) { props.onMouseDown?.(event); state.close() },
      onClick(event: EventPayload) { props.onClick?.(event); state.close() },
      onFocus(event: EventPayload) { props.onFocus?.(event); state.openNow() },
      onBlur(event: EventPayload) { props.onBlur?.(event); state.close() },
    },
    defaultTabIndex: 0,
  })
}

export interface TooltipContentProps extends FloatingContentProps {}
export function TooltipContent(props: TooltipContentProps): JSX.Element {
  const state = context("TooltipContent")
  return createComponent(Show, {
    get when() { return state.open() },
    keyed: true,
    get children() {
      return createComponent(DismissableLayer, {
        onEscapeKeyDown: state.close,
        get children() {
          return FloatingLayer({
            ...props,
            side: props.side ?? "top",
            align: props.align ?? "center",
            onMouseEnter(event) {
              props.onMouseEnter?.(event)
              if (state.hoverable) state.cancelClose()
            },
            onMouseLeave(event) {
              props.onMouseLeave?.(event)
              state.scheduleClose()
            },
          })
        },
      })
    },
  })
}

export {
  Tooltip as Root,
  TooltipContent as Content,
  TooltipProvider as Provider,
  TooltipTrigger as Trigger,
}
